package pl.moderr.eduscript.interpreter.type;

import java.io.Serializable;

public enum TokenType implements Serializable {
  ASSIGN, DECIMAL, DIVIDE, END, FALSE, IDENTIFIER, INTEGER, LPARA, MINUS, MODULO, MULTIPLY, PLUS, POWER, RPARA, SEPARATOR, STRING, TRUE, IF, LCURLY, RCURLY, ASSIGN_PLUS, ASSIGN_MINUS, ASSIGN_MULTIPLY, ASSIGN_DIVIDE, ASSIGN_MODULO, ASSIGN_POWER, EQUAL, NOT_EQUAL, NEGATE, GREATER, LESS, LESS_EQUAL, GREATER_EQUAL, AND, OR, DIVIDED, ELSE, WHILE, LBRACKET, RBRACKET, CONTAINS, FILE_END

}
